{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fizzbuzz.serviceAccountName" . }}
  labels:
{{ include "fizzbuzz.labels" . | indent 4 }}
{{- end -}}
